# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f601cb8a21af270d2e2a535017eca89ec3f2fef59d164649b29dc9ee2d74fc9d627b199766c2244eeec820788804f406cc8b6f447d73d05de21f08ce61822d1

test:
  secret_key_base: d79455c07f8286f43539fa30938c1e07f4966ade1f1914498fda15424c0787c98777acec297afda7d988bfd30fbd77cf4306761dd78cd5a90b17b77c84f2050d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
